#!/usr/bin/bash -x
zfs create -o mountpoint=/repo -o compress=on rpool/repo
pkgrepo create /repo
xargs pkgrecv -s http://pkg.oracle.com/solaris/release -d /repo << PKGLIST
pkg://solaris/compress/bzip2
pkg://solaris/compress/gzip
pkg://solaris/compress/p7zip
pkg://solaris/compress/unzip
pkg://solaris/compress/xz
pkg://solaris/compress/zip
pkg://solaris/consolidation/SunVTS/SunVTS-incorporation
pkg://solaris/consolidation/X/X-incorporation
pkg://solaris/consolidation/admin/admin-incorporation
pkg://solaris/consolidation/cacao/cacao-incorporation
pkg://solaris/consolidation/cde/cde-incorporation
pkg://solaris/consolidation/cns/cns-incorporation
pkg://solaris/consolidation/dbtg/dbtg-incorporation
pkg://solaris/consolidation/desktop/desktop-incorporation
pkg://solaris/consolidation/desktop/gnome-incorporation
pkg://solaris/consolidation/gfx/gfx-incorporation
pkg://solaris/consolidation/install/install-incorporation
pkg://solaris/consolidation/ips/ips-incorporation
pkg://solaris/consolidation/java/java-incorporation
pkg://solaris/consolidation/jdmk/jdmk-incorporation
pkg://solaris/consolidation/l10n/l10n-incorporation
pkg://solaris/consolidation/man/man-incorporation
pkg://solaris/consolidation/nspg/nspg-incorporation
pkg://solaris/consolidation/nvidia/nvidia-incorporation
pkg://solaris/consolidation/osnet/osnet-incorporation
pkg://solaris/consolidation/sfw/sfw-incorporation
pkg://solaris/consolidation/sic_team/sic_team-incorporation
pkg://solaris/consolidation/solaris_re/solaris_re-incorporation
pkg://solaris/consolidation/sunpro/sunpro-incorporation
pkg://solaris/consolidation/ub_javavm/ub_javavm-incorporation
pkg://solaris/consolidation/userland/userland-incorporation
pkg://solaris/consolidation/vpanels/vpanels-incorporation
pkg://solaris/consolidation/xvm/xvm-incorporation
pkg://solaris/crypto/ca-certificates
pkg://solaris/database/berkeleydb-5
pkg://solaris/database/mysql-51
pkg://solaris/database/mysql-51/library
pkg://solaris/database/mysql-common
pkg://solaris/database/sqlite-3
pkg://solaris/developer/base-developer-utilities
pkg://solaris/developer/debug/mdb
pkg://solaris/developer/macro/cpp
pkg://solaris/diagnostic/cpu-counters
pkg://solaris/diagnostic/snoop
pkg://solaris/diagnostic/tcpdump
pkg://solaris/editor/vim/vim-core
pkg://solaris/entire
pkg://solaris/file/gnu-coreutils
pkg://solaris/group/feature/amp
pkg://solaris/group/system/solaris-small-server
pkg://solaris/image/library/libjpeg
pkg://solaris/image/library/libpng
pkg://solaris/library/apr-13
pkg://solaris/library/apr-util-13
pkg://solaris/library/apr-util-13/apr-ldap
pkg://solaris/library/apr-util-13/dbd-mysql
pkg://solaris/library/apr-util-13/dbd-sqlite
pkg://solaris/library/database/gdbm
pkg://solaris/library/expat
pkg://solaris/library/gmp
pkg://solaris/library/libffi
pkg://solaris/library/libidn
pkg://solaris/library/libmilter
pkg://solaris/library/libtecla
pkg://solaris/library/libtool/libltdl
pkg://solaris/library/libxml2
pkg://solaris/library/libxslt
pkg://solaris/library/ncurses
pkg://solaris/library/nspr
pkg://solaris/library/openldap
pkg://solaris/library/perl-5/sun-solaris-512
pkg://solaris/library/python-2/cherrypy
pkg://solaris/library/python-2/cherrypy-26
pkg://solaris/library/python-2/jsonrpclib
pkg://solaris/library/python-2/jsonrpclib-26
pkg://solaris/library/python-2/libxml2-26
pkg://solaris/library/python-2/libxsl-26
pkg://solaris/library/python-2/lxml
pkg://solaris/library/python-2/lxml-26
pkg://solaris/library/python-2/m2crypto
pkg://solaris/library/python-2/m2crypto-26
pkg://solaris/library/python-2/mako
pkg://solaris/library/python-2/mako-26
pkg://solaris/library/python-2/net-snmp-26
pkg://solaris/library/python-2/ply
pkg://solaris/library/python-2/ply-26
pkg://solaris/library/python-2/pybonjour
pkg://solaris/library/python-2/pybonjour-26
pkg://solaris/library/python-2/pycurl
pkg://solaris/library/python-2/pycurl-26
pkg://solaris/library/python-2/pyopenssl
pkg://solaris/library/python-2/pyopenssl-26
pkg://solaris/library/python-2/python-extra-26
pkg://solaris/library/python-2/simplejson-26
pkg://solaris/library/readline
pkg://solaris/library/security/nss
pkg://solaris/library/security/openssl
pkg://solaris/library/security/openssl/openssl-fips-140
pkg://solaris/library/security/trousers
pkg://solaris/library/zlib
pkg://solaris/media/cdrtools
pkg://solaris/media/xorriso
pkg://solaris/naming/ldap
pkg://solaris/network/bridging
pkg://solaris/network/dns/bind
pkg://solaris/network/ipfilter
pkg://solaris/network/open-fabrics
pkg://solaris/network/ping
pkg://solaris/network/rsync
pkg://solaris/network/ssh
pkg://solaris/network/ssh/ssh-key
pkg://solaris/package/pkg
pkg://solaris/package/pkg/zones-proxy
pkg://solaris/package/svr4
pkg://solaris/release/name
pkg://solaris/release/notices
pkg://solaris/runtime/perl-512
pkg://solaris/runtime/python-26
pkg://solaris/security/nss-utilities
pkg://solaris/security/sudo
pkg://solaris/security/tcp-wrapper
pkg://solaris/service/file-system/nfs
pkg://solaris/service/network/dns/mdns
pkg://solaris/service/network/smtp/sendmail
pkg://solaris/service/network/ssh
pkg://solaris/service/security/gss
pkg://solaris/service/security/kerberos-5
pkg://solaris/shell/bash
pkg://solaris/shell/ksh
pkg://solaris/shell/ksh93
pkg://solaris/system/boot-environment-utilities
pkg://solaris/system/boot/wanboot
pkg://solaris/system/core-os
pkg://solaris/system/data/terminfo/terminfo-core
pkg://solaris/system/data/timezone
pkg://solaris/system/device-administration
pkg://solaris/system/dtrace
pkg://solaris/system/dtrace/dtrace-toolkit
pkg://solaris/system/fault-management
pkg://solaris/system/fault-management/fm-snmp-mib
pkg://solaris/system/fault-management/smtp-notify
pkg://solaris/system/file-system/autofs
pkg://solaris/system/file-system/hsfs
pkg://solaris/system/file-system/nfs
pkg://solaris/system/file-system/pcfs
pkg://solaris/system/file-system/udfs
pkg://solaris/system/file-system/ufs
pkg://solaris/system/file-system/zfs
pkg://solaris/system/install
pkg://solaris/system/install/auto-install/auto-install-common
pkg://solaris/system/install/configuration
pkg://solaris/system/install/locale
pkg://solaris/system/kernel
pkg://solaris/system/library
pkg://solaris/system/library/boot-management
pkg://solaris/system/library/c++-runtime
pkg://solaris/system/library/freetype-2
pkg://solaris/system/library/gcc-3-runtime
pkg://solaris/system/library/iconv/utf-8
pkg://solaris/system/library/install
pkg://solaris/system/library/libpcap
pkg://solaris/system/library/math
pkg://solaris/system/library/openmp
pkg://solaris/system/library/security/gss
pkg://solaris/system/library/security/gss/diffie-hellman
pkg://solaris/system/library/security/gss/spnego
pkg://solaris/system/library/security/libmcrypt
pkg://solaris/system/library/security/libsasl
pkg://solaris/system/library/security/rpcsec
pkg://solaris/system/library/storage/libdiskmgt
pkg://solaris/system/library/storage/scsi-plugins
pkg://solaris/system/library/storage/snia-ima
pkg://solaris/system/library/storage/suri
pkg://solaris/system/linker
pkg://solaris/system/locale
pkg://solaris/system/management/snmp/net-snmp
pkg://solaris/system/manual
pkg://solaris/system/manual/locale
pkg://solaris/system/network
pkg://solaris/system/network/nis
pkg://solaris/system/network/routing
pkg://solaris/system/prerequisite/gnu
pkg://solaris/system/resource-mgmt/resource-caps
pkg://solaris/system/resource-mgmt/resource-pools
pkg://solaris/system/storage/iscsi/iscsi-initiator
pkg://solaris/system/system-events
pkg://solaris/system/xopen/xcu4
pkg://solaris/system/zones
pkg://solaris/system/zones/brand/brand-solaris
pkg://solaris/terminal/luit
pkg://solaris/terminal/resize
pkg://solaris/text/doctools
pkg://solaris/text/doctools/ja
pkg://solaris/text/groff/groff-core
pkg://solaris/text/less
pkg://solaris/text/spelling-utilities
pkg://solaris/text/tidy
pkg://solaris/web/curl
pkg://solaris/web/php-52
pkg://solaris/web/php-52/extension/php-apc
pkg://solaris/web/php-52/extension/php-idn
pkg://solaris/web/php-52/extension/php-memcache
pkg://solaris/web/php-52/extension/php-mysql
pkg://solaris/web/php-52/extension/php-pear
pkg://solaris/web/php-52/extension/php-suhosin
pkg://solaris/web/php-52/extension/php-tcpwrap
pkg://solaris/web/php-52/extension/php-xdebug
pkg://solaris/web/php-common
pkg://solaris/web/server/apache-22
pkg://solaris/web/server/apache-22/module/apache-dtrace
pkg://solaris/web/server/apache-22/module/apache-fcgid
pkg://solaris/web/server/apache-22/module/apache-php5
pkg://solaris/web/server/apache-22/module/apache-php52
pkg://solaris/web/wget
pkg://solaris/x11/header/x11-protocols
pkg://solaris/x11/library/libfontenc
pkg://solaris/x11/library/libice
pkg://solaris/x11/library/libpthread-stubs
pkg://solaris/x11/library/libsm
pkg://solaris/x11/library/libx11
pkg://solaris/x11/library/libxau
pkg://solaris/x11/library/libxcb
pkg://solaris/x11/library/libxdmcp
pkg://solaris/x11/library/libxevie
pkg://solaris/x11/library/libxext
pkg://solaris/x11/library/libxpm
pkg://solaris/x11/library/libxscrnsaver
pkg://solaris/x11/library/toolkit/libxt
pkg://solaris/image/gnuplot
pkg://solaris/library/gd
pkg://solaris/library/graphics/wxwidgets
pkg://solaris/library/sdl
pkg://solaris/runtime/lua
pkg://solaris/consolidation/java/java-incorporation@0.5.11,5.11-0.175.1.0.0.24.0:20120904T175431Z
PKGLIST
pkgrepo rebuild -s /repo
svccfg -s application/pkg/server setprop pkg/inst_root=/repo   
svcprop -p pkg/inst_root application/pkg/server
svcadm refresh application/pkg/server 
svcadm enable application/pkg/server 
pkg set-publisher -G '*' -M '*' -g http://10.0.2.15/ solaris

